package com.project.integradorII.entities;

public enum SpecialtyEnum {
    CARDIOLOGIST,
    DERMATOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    GENERAL_PRACTITIONER,
    GYNECOLOGIST,
    NEUROLOGIST,
    OPHTHALMOLOGIST,
    ORTHOPEDIST,
    PEDIATRICIAN,
    PSYCHIATRIST,
    PULMONOLOGIST,
    RHEUMATOLOGIST,
    UROLOGIST
}
